---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role hadoop_common
# 

#
# vars are namespace with the module name.
#

HADOOP_COMMON_VERSION: 2.3.0
HADOOP_COMMON_USER_HOME: /home/hadoop
HADOOP_COMMON_HOME: "{{ HADOOP_COMMON_USER_HOME }}/hadoop"
HADOOP_COMMON_DATA: /var/lib/hadoop/hdfs
HADOOP_COMMON_CONF_DIR: "{{ HADOOP_COMMON_HOME }}/etc/hadoop"
HADOOP_COMMON_PROTOBUF_VERSION: 2.5.0 

hadoop_common_role_name: hadoop_common
hadoop_common_user: hadoop
hadoop_common_group: hadoop
hadoop_common_dist:
  filename: "hadoop-{{ HADOOP_COMMON_VERSION }}.tar.gz"
  url: "https://archive.apache.org/dist/hadoop/core/hadoop-{{ HADOOP_COMMON_VERSION }}/hadoop-{{ HADOOP_COMMON_VERSION }}.tar.gz"
  sha256sum: 3fad58b525a47cf74458d0996564a2151c5a28baa1f92383e7932774deef5023
hadoop_common_protobuf_dist:
  filename: "protobuf-{{ HADOOP_COMMON_PROTOBUF_VERSION }}.tar.gz"
  url: "https://protobuf.googlecode.com/files/protobuf-{{ HADOOP_COMMON_PROTOBUF_VERSION }}.tar.gz"
  sha256sum: c55aa3dc538e6fd5eaf732f4eb6b98bdcb7cedb5b91d3b5bdcf29c98c293f58e
hadoop_common_java_home: /usr/lib/jvm/java-7-openjdk-amd64

#
# OS packages
#

hadoop_common_debian_pkgs:
  - llvm-gcc
  - build-essential
  - make
  - cmake
  - automake
  - autoconf
  - libtool
  - zlib1g-dev
  - openjdk-7-jdk
  - maven

hadoop_common_redhat_pkgs: []
